<main class="index-container">
    <h1 class="index-container__title">Motus</h1>
    <div class="index-container__text">
        <p>Bienvenue sur ce site web ou vous allez pouvoir jouer à un jeu directement inspiré du jeu télévisé motus.</p>
        <p>Les règles sont simples, vous avez droit à six tentatives pour trouver un mot composé de 6 lettres. La première lettre vous est donnée.</p>
        <p>Si trouvez le mot, vous aurez accès au Quitte ou Double; Quitte vous permettra de vous arrêter et d'enregistrer votre score; Double vous offre l'opportunité de continuer pour faire grimper votre score, mais attention! En cas d'échec, votre score retombera à zéro.</p>
    </div>
    <div class="index-container__btn">
        <a class="btn btn-secondary" href="/motus/Users/game">Jouer</a>
        <a class="btn btn-secondary" href="/motus/Score/displayScore">Voir le Wall of Fame</a>
    </div>
</main>